FROM alpine:3.10
LABEL org.label-schema.name="docker-alpine-rust" \
    org.label-schema.description="Docker Alpine Rust Cargo" \
    org.label-schema.url="https://hub.docker.com/r/sitkevij/alpine-rust/" \
    org.label-schema.usage="https://github.com/sitkevij/alpine-rust/blob/master/README.md" \
    org.label-schema.vcs-url="https://github.com/sitkevij/alpine-rust" \
    org.label-schema.vendor="sitkevij" \
    org.label-schema.version="0.2.0" \
    maintainer="https://github.com/sitkevij"

RUN apk add --no-cache gcc musl-dev && apk add --no-cache rust cargo